#!/bin/bash
#  Mounts firefox profile into tmpfs before running, then syncs it back after running

FASTNAME=sexyfox
PROFILE=`basename $0|sed -s 's/^'$FASTNAME'-//'`
if [ "$PROFILE" = "$FASTNAME" ]; then PROFILE=default; fi
USER=`whoami`
LOCKNAME=mozilla
TMPDIR=.mozilla
APPNAME=firefox
TMPFS=/tmp/$USER
LOCKDIR=$HOME/.$FASTNAME/lock
PLOCK=$LOCKDIR/$LOCKNAME-$PROFILE
SYNC_WAIT=300   # sync every 5 minutes

function sexyfox_myprofile_running () {
	if [ -f "$PLOCK" ]; then
		return 0 # lock found, sexyfox-profile is running
	else
		return 1 # lock not found
	fi
}

function sexyfox_profiledirname () {
	(
	cd $HOME/$TMPDIR/$APPNAME
	find -maxdepth 1 -name "*.$PROFILE" \( -type d -or -type l \) -exec basename {} \;  2>/dev/null
	)
}

function prev_profile () {
	echo -n "$HOME_PROFILE.previous"
}
function curr_profile () {
	echo -n "$HOME_PROFILE.current"
}

function sexyfox_sync_current () {
	echo "Syncing tmpfs back to current profile directory... ($(curr_profile)) "
	cat <<-'SAFETY_PIG'
		Note: this means we're syncing any open sqlite databases into the current profile.
		I'm not sure that's a good idea, so here's a safety pig.
		
		 _._ _..._ .-',     _.._(`))
		'-. `     '  /-._.-'    ',/
		   )         \            '.
		  / _    _    |             \
		 |  a    a    /              |
		 \   .-.                     ;
		  '-('' ).-'       ,'       ;
		     '-;           |      .'
		        \           \    /
		        | 7  .__  _.-\   \
		        | |  |  ``/  /`  /
		       /,_|  |   /,_/   /
		          /,_/      '`-'
	SAFETY_PIG
	sleep $SYNC_WAIT
	rsync -av --progress --delete "$TEMP_PROFILE/" "$(curr_profile)"
}

# sleeps either until sync or lock file is removed
function sexyfox_sync_wait () {
	WAIT=$1
	for ((x=0; $x<$WAIT; x=$x+1)); do
		if ! [ -f $PLOCK ]; then
			return 1 # dont sync
		fi
		sleep 1
	done
	return 0
}

# returns true on improper shutdown
function sexyfox_improper_shutdown () {
	# lock file exists,
	# home profile is a symlink to the temp profile
	# temp profile doesn't exist
	if sexyfox_myprofile_running && \
	   [ "$TEMP_PROFILE" = "$(readlink $HOME_PROFILE)" ] && \
	   ! [ -d "$TEMP_PROFILE" ]; then
	  return 0 # improper shutdown
	fi
	return 1 # proper shutdown
}

#########################################################

PROFILEDIR="$TMPDIR/$APPNAME/$(sexyfox_profiledirname)"
TEMP_PROFILE="$TMPFS/$PROFILEDIR"
HOME_PROFILE="$HOME/$PROFILEDIR"

# if the original directory is a symlink, reference the symlink target instead
if [ -h "$HOME_PROFILE" ]; then
	if readlink "$HOME_PROFILE" | egrep -q '^/'; then
		#absolute path
		HOME_PROFILE=$(readlink "$HOME_PROFILE"|sed 's|/$||')
	else
		#relative path
		HOME_PROFILE=$(dirname "$HOME_PROFILE")/$(readlink "$HOME_PROFILE"|sed 's|/$||')
	fi
fi

# check for improperly shut down sexyfoxen
if sexyfox_improper_shutdown; then
	echo "Improper shutdown detected, using previous profile"

	# remove the lock file
	rm -v $PLOCK
	
	# remove the symlink
	rm -v $HOME_PROFILE
	
	# use the previous profile
	mv -v $(prev_profile) $HOME_PROFILE
fi

# link files under current profile to tmpfs directory.
if ! sexyfox_myprofile_running; then
	STARTER="starter"
	mkdir -pv $LOCKDIR
	touch $PLOCK
	cd $HOME/

	if ! [ -d "$TMPFS" ]; then mkdir -pv "$TMPFS"; fi

	echo "Cleaning up previous backups..."
	rm -Rvf "$(prev_profile)"

	echo "Syncing current directory to tmpfs..."
	mkdir -pv $TEMP_PROFILE
	rsync -av --progress --delete "$HOME_PROFILE/" "$TEMP_PROFILE"

	echo "Swapping home profile with tmpfs"
	mv -v "$HOME_PROFILE" "$(prev_profile)"
	rsync -av "$(prev_profile)" "$(curr_profile)"
	ln -sv "$TEMP_PROFILE" "$HOME_PROFILE"

	echo "Starting periodic resyncer"
	(
		while sexyfox_sync_wait $SYNC_WAIT; do
			sexyfox_sync_current
		done
	) &
fi

# run sexyfox with the given arguments
$APPNAME -P $PROFILE $*

# if we're the instance that started this profile, and we just exited, we have the right to sync back
if [ "$STARTER" ]; then
	cd $TMPFS/

	echo "Syncing tmpfs back to profile directory... ($HOME_PROFILE)"
	rm -v "$HOME_PROFILE"
	rsync -av --progress --delete "$TEMP_PROFILE/" "$HOME_PROFILE"

	# remove the lock on the profile
	rm -v $PLOCK
fi
